module.exports = {
    SET_SENSORS: "SET_SENSORS",
    SET_SENSOR_TYPE: "SET_SENSOR_TYPE",
    SET_SENSOR_NAME: "SET_SENSOR_NAME",
    SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
    SET_SORT_BY: "SET_SORT_BY"
}
